// pulling data from totalcso currently, unsure how to get this with in game command
// https://totalcsgo.com/binds/keys
// console.log(JSON.stringify([...document.querySelectorAll("#table > tbody > tr")].map(row => [...row.querySelectorAll('td')].map(data => data.innerHTML )).map(([name, code]) => ({name, code}))))
export default [
	{ name: '1 / End', code: 'kp_end' },
	{ name: '2 / Down Arrow', code: 'kp_downarrow' },
	{ name: '3 / Page Down', code: 'kp_pgdn' },
	{ name: '4 / Left Arrow', code: 'kp_leftarrow' },
	{ name: '5', code: 'kp_5' },
	{ name: '6 / Right Arrow', code: 'kp_rightarrow' },
	{ name: '7 / Home', code: 'kp_home' },
	{ name: '8 / Up Arrow', code: 'kp_uparrow' },
	{ name: '9 / Page Up', code: 'kp_pgup' },
	{ name: '0 / Insert', code: 'kp_ins' },
	{ name: '. / Delete', code: 'kp_del' },
	{ name: '/ (Slash)', code: 'kp_slash' },
	{ name: '* (Multiply)', code: 'kp_multiply' },
	{ name: '- (Minus)', code: 'kp_minus' },
	{ name: '+ (Plus)', code: 'kp_plus' },
	{ name: 'Enter', code: 'kp_enter' },
	{ name: 'Insert', code: 'ins' },
	{ name: 'Delete', code: 'del' },
	{ name: 'Home', code: 'home' },
	{ name: 'End', code: 'end' },
	{ name: 'Page Up', code: 'pgup' },
	{ name: 'Page Down', code: 'pgdn' },
	{ name: 'Up Arrow', code: 'uparrow' },
	{ name: 'Left Arrow', code: 'leftarrow' },
	{ name: 'Down Arrow', code: 'downarrow' },
	{ name: 'Right Arrow', code: 'rightarrow' },
	{ name: 'F1', code: 'f1' },
	{ name: 'F2', code: 'f2' },
	{ name: 'F3', code: 'f3' },
	{ name: 'F4', code: 'f4' },
	{ name: 'F5', code: 'f5' },
	{ name: 'F6', code: 'f6' },
	{ name: 'F7', code: 'f7' },
	{ name: 'F8', code: 'f8' },
	{ name: 'F9', code: 'f9' },
	{ name: 'F10', code: 'f10' },
	{ name: 'F11', code: 'f11' },
	{ name: 'F12', code: 'f12' },
	{ name: '1 / ! (Exclamation Mark)', code: '1' },
	{ name: '2 / @ (At Sign)', code: '2' },
	{ name: '3 / # (Number Sign)', code: '3' },
	{ name: '4 / $ (Dollar Sign)', code: '4' },
	{ name: '5 / % (Percent Sign)', code: '5' },
	{ name: '6 / ^ (Caret)', code: '6' },
	{ name: '7 / &amp; (Ampersand)', code: '7' },
	{ name: '8 / * (Asterisk)', code: '8' },
	{ name: '9 / ( (Parenthesis Left)', code: '9' },
	{ name: '0 / ) (Parenthesis Right)', code: '0' },
	{ name: 'A', code: 'a' },
	{ name: 'B', code: 'b' },
	{ name: 'C', code: 'c' },
	{ name: 'D', code: 'd' },
	{ name: 'E', code: 'e' },
	{ name: 'F', code: 'f' },
	{ name: 'G', code: 'g' },
	{ name: 'H', code: 'h' },
	{ name: 'I', code: 'i' },
	{ name: 'J', code: 'j' },
	{ name: 'K', code: 'k' },
	{ name: 'L', code: 'l' },
	{ name: 'M', code: 'm' },
	{ name: 'N', code: 'n' },
	{ name: 'O', code: 'o' },
	{ name: 'P', code: 'p' },
	{ name: 'Q', code: 'q' },
	{ name: 'R', code: 'r' },
	{ name: 'S', code: 's' },
	{ name: 'T', code: 't' },
	{ name: 'U', code: 'u' },
	{ name: 'V', code: 'v' },
	{ name: 'W', code: 'w' },
	{ name: 'X', code: 'x' },
	{ name: 'Y', code: 'y' },
	{ name: 'Z', code: 'z' },
	{ name: 'Space Bar', code: 'space' },
	{ name: '- (Hyphen) / _ (Underscore)', code: '-' },
	{ name: '= (Equals Sign) / + (Plus Sign)', code: '=' },
	{ name: '[ (Bracket Left) / { (Brace Left)', code: '[' },
	{ name: '] (Bracket Right) / } (Brace Right)', code: ']' },
	{ name: '\\ (Backslash) / | (Pipe)', code: '\\' },
	{ name: '; (Semicolon) / : (Colon)', code: 'semicolon' },
	{ name: '\' (Apostraphe) / " (Quotation Marks)', code: "'" },
	{ name: ', (Comma) / &lt; (Pointy Bracket Left)', code: ',' },
	{ name: '. (Period) / &gt; (Pointy Bracket Right)', code: '.' },
	{ name: '/ (Slash) / ? (Question Mark)', code: '/' },
	{ name: 'Backspace', code: 'backspace' },
	{ name: 'Tab', code: 'tab' },
	{ name: 'Enter', code: 'enter' },
	{ name: 'Caps Lock', code: 'capslock' },
	{ name: 'Shift Left', code: 'shift' },
	{ name: 'Shift Right', code: 'rshift' },
	{ name: 'Control Left', code: 'ctrl' },
	{ name: 'Control Right', code: 'rctrl' },
	{ name: 'Alt Left', code: 'alt' },
	{ name: 'Alt Right', code: 'ralt' },
	{ name: 'Left Mouse', code: 'mouse1' },
	{ name: 'Right Mouse', code: 'mouse2' },
	{ name: 'Middle Mouse', code: 'mouse3' },
	{ name: 'Side Mouse 1', code: 'mouse4' },
	{ name: 'Side Mouse 2', code: 'mouse5' },
	{ name: 'Mouse Wheel Down', code: 'mwheeldown' },
	{ name: 'Mouse Wheel Up', code: 'mwheelup' },
];
